steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      ls
      gsutil cp -r storage gs://khanhs-test-bucket/
options:
  logging: CLOUD_LOGGING_ONLY
