steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      ls
      gsutil cp storage/flutter-survey-metadata.json gs://khanh-sandbox-bucket/flutter-survey-metadata.json
options:
  logging: CLOUD_LOGGING_ONLY
